services:
  app:
    container_name: nestjs-app-mongodb
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/nestdb
    networks:
      - app-networks
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - '27017-27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-networks

volumes:
  mongodb_data:

networks:
  app-networks: