services:
  super-app:
    build: .
    ports:
      - '5000:3000'
    env_file:
      - .env
    depends_on:
      - super-db
    networks:
      - super-net
  super-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=saman77071!
      - POSTGRES_DB=besicp
    ports:
      - '5433:5432'
    networks:
      - super-net

networks:
  super-net:
    driver: bridge
