import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import { ReduxProvider } from "@/providers/redux-provider";
import { SessionProvider } from "next-auth/react";
import AppProvider from "@/providers/app-provider";

const latoFont = Lato({
  variable: "--font-sans-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <AppProvider>
          <html lang="en">
        <body className={`${latoFont.variable} antialiased`}>
            <div className="min-h-screen , flex flex-col justify-between">
              <div>
                <Header />
                {children}
              </div>
              <Footer />
            </div>
        </body>
      </html>
   </AppProvider>


  );
}
